name: CI (browser)

on:
  push:
    paths:
      - 'packages/engine.io-parser/**'
      - 'packages/engine.io-client/**'
      - 'packages/socket.io-parser/**'
      - 'packages/socket.io-client/**'

permissions:
  contents: read

jobs:
  test-browser:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm ci

      - name: Compile each package
        run: pnpm run compile --recursive

      - name: Run tests
        run: npm test --workspace=socket.io-parser --workspace=socket.io-client
        env:
          BROWSERS: 1
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
